services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: webapp
    ports:
      - "8181:8181"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # Don't sync node_modules from host
      - /app/node_modules
    environment:
      - APP_PORT=8181
      - NODE_ENV=development
    command: npm run dev
    # Keep container running if nodemon crashes
    restart: unless-stopped

  smtp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smtp-dev
    command: node src/smtp-dev.js
    ports:
      - "2525:2525"
    volumes:
      - ./src:/app/src
    tty: true
    stdin_open: true 